# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafModel',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
            ],
            options={
                'abstract': False,
            },
            bases=('jmbo.modelbase',),
        ),
    ]
