# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmbo', '0002_auto_20160530_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelbaseimage',
            options={'ordering': ('position',)},
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='crop_from',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='image',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='view_count',
        ),
    ]
