# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmbo', '0005_modelbase_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='imageoverride',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmbo.Image'),
        ),
        migrations.AddField(
            model_name='imageoverride',
            name='photo_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.PhotoSize'),
        ),
        migrations.AlterUniqueTogether(
            name='imageoverride',
            unique_together=set([('image', 'photo_size')]),
        ),
    ]
