# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import photologue.models


class Migration(migrations.Migration):

    dependencies = [
        ('jmbo', '0006_auto_20170206_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoverride',
            name='replacement',
            field=models.ImageField(upload_to=photologue.models.get_storage_path),
        ),
    ]
