# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:12
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jmbo', '0007_auto_20170314_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbase',
            name='images',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, sort_value_field_name=b'position', through='jmbo.ModelBaseImage', to='jmbo.Image'),
        ),
    ]
